### ISSUE TITLE
I build your source code in my project,and get this problem when checking mem leak.why?

### ISSUE THREAD

**Issue by wangsheng115** [liaohuqiu/leakcanary-demo#4]
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
    at com.squareup.leakcanary.HeapAnalyzer.findLeakingReference(HeapAnalyzer.java:160)
    at com.squareup.leakcanary.HeapAnalyzer.checkForLeak(HeapAnalyzer.java:95)
    at com.squareup.leakcanary.internal.HeapAnalyzerService.onHandleIntent(HeapAnalyzerService.java:57)
    at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
    at android.os.Handler.dispatchMessage(Handler.java:111)
    at android.os.Looper.loop(Looper.java:207)
    at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by xxlyu-2046** [comment]
may be the Android API  level problem,try to run it on lower API

**Comment by ZJsnowman** [comment]
@xiadeye you are right .change a phone with lower api

**Comment by Lee-swifter** [comment]
I got this problem on my xiaomi (api 23), but when I tested this on an old phone (api 19), it worked OK.
I think you need to use a older phone to test as @xiadeye said.
