### ISSUE TITLE
FATAL EXCEPTION: IntentService[HeapAnalyzerService]

### ISSUE THREAD

**Issue by plastic-kai** [liaohuqiu/leakcanary-demo#6]
download the app, run on both Nexus 3 and Nexus 6p, both errors:

demo.leakcanary.srain.in.leakcanarydemo:leakcanary E/AndroidRuntime: FATAL EXCEPTION: IntentService[HeapAnalyzerService]
                                                                                                    Process: demo.leakcanary.srain.in.leakcanarydemo:leakcanary, PID: 24031
                                                                                                    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
                                                                                                        at com.squareup.leakcanary.HeapAnalyzer.findLeakingReference(HeapAnalyzer.java:154)
                                                                                                        at com.squareup.leakcanary.HeapAnalyzer.checkForLeak(HeapAnalyzer.java:89)
                                                                                                        at com.squareup.leakcanary.internal.HeapAnalyzerService.onHandleIntent(HeapAnalyzerService.java:56)
                                                                                                        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
                                                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                        at android.os.Looper.loop(Looper.java:148)
                                                                                                        at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by Ignorance-Panda** [comment]
both on Nexus 5x, Android N
